# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('technologies', models.CharField(max_length=300)),
                ('designer', models.CharField(max_length=300)),
                ('screenshot', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
