# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awaards', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awaards.Profile'),
        ),
        migrations.AddField(
            model_name='designrating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awaards.Project'),
        ),
        migrations.AddField(
            model_name='designrating',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
