# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0006_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
