# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0008_auto_20190701_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
